### ISSUE TITLE
awx-python not available

### ISSUE THREAD

**Issue by rverhe** [ansible/awx-custom-credential-plugin-example#1]
Hello,

awx-python command is not available in the newest awx install.

How to integrate my custom plugin in AWX?
Did it with the --extra-vars in a custom venv, but awx does not regornize it.
How to embed this in my helm deployment?

**Comment by ryanpetrello** [comment]
`awx-python` this needs to be run from _within_ the task container (where `awx-python` is available), not your host machine.

**Comment by MalfuncEddie** [comment]
And how do you do This with the new execution envs. ?

Ansible builder?
